- README.md
- index.js
- lib/config-factory.js
- lib/handlers.js
- test/config-factory.spec.js
- test/http-proxy-middleware.spec.js
> Shorthand support

- index.js
- test/http-proxy-middleware.spec.js
Support different ways of mounting with express/connect (#17)
> Support mounting when connect/express path is configured.

- README.md
- index.js
- lib/config-factory.js
- test/config-factory.spec.js
- test/websocket.spec.js
External websocket server http upgrade (#19)
> External websocket server http upgrade

- index.js
> fixed: path rewrite when agent is used.

- README.md
- index.js
- lib/config-factory.js
- lib/logger.js
- lib/path-rewriter.js
- lib/proxy-table.js
- test/http-proxy-middleware.spec.js
- test/logger.spec.js
> feat: log levels & log provider

- index.js
- lib/handlers.js
> fix(handlers.js): server crash when target ws server closes.

- CHANGELOG.md
- README.md
- index.js
- lib/config-factory.js
- recipes/basic.md
- test/config-factory.spec.js
- test/http-proxy-middleware.spec.js
Create proxy without `context` parameter; using server's `path` config instead:
```javascript
app.use('/api', proxy('http://localhost:3000', {changeOrigin:true}));
```
```javascript
app.use('/api', proxy({target: 'http://localhost:3000', changeOrigin:true}));
```
> feat(proxy): allow contextless proxy configuration

- CHANGELOG.md
- index.js
- lib/index.js
- package.json
> fix(websocket): fixes websocket upgrade when both config.ws and external .upgrade() are used

- CHANGELOG.md
- README.md
- lib/context-matcher.js
- package.json
- recipes/context-matching.md
- test/unit/context-matcher.spec.js
fixes #86 
[RFC 3986 path](https://tools.ietf.org/html/rfc3986#section-3.3) is used for context matching. Query parameters are ignored.
This also aligns with Express http://expressjs.com/en/guide/routing.html
> Query strings are not part of the route path.
> fix(context matching): Use `RFC 3986 path` (excludes query parameters)

- CHANGELOG.md
- lib/index.js
- test/e2e/express-router.spec.js
fixes #94 
`req.url` get rewritten even for non proxy routes.
Fix:
Only rewrite `req.url` when proxy routes matches.
> fix(Express Router): breaking unmatched paths (non proxy routes)

- lib/index.js
- package.json
This will add error description when logging errors. 
1. The error descriptions are "standard" descriptions supported by Node module [errno](https://www.npmjs.com/package/errno), see Node [Common System Errors](https://nodejs.org/api/errors.html#errors_class_system_error) and [POSIX errno](http://man7.org/linux/man-pages/man3/errno.3.html)
2. The error message format is also slightly modified, hopefully to be more beginner friendly. See an error example in the console of a [create-react-app](https://github.com/facebookincubator/create-react-app) test application.
HPM is used by create-react-app for [Proxying API Requests](https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#proxying-api-requests-in-development). …
> feat(logging): improve error message & add link to Node errors page.

- lib/index.js
> bug(websocket): memory leak when option 'ws:true' is used.

- lib/index.js
fix #39 - proxy ntlm authentication
```
_stream_writable.js:361
cb();
^
TypeError: cb is not a function
at afterWrite (_stream_writable.js:361:3)
at onwrite (_stream_writable.js:352:7)
at WritableState.onwrite (_stream_writable.js:89:5)
at Socket._writeGeneric (net.js:714:5)
at Socket._write (net.js:724:8)
at doWrite (_stream_writable.js:307:12)
at writeOrBuffer (_stream_writable.js:293:5)
at Socket.Writable.write (_stream_writable.js:220:11)
at Socket.write (net.js:650:40)
at ClientRequest.OutgoingMessage._writeRaw (_http_outgoing.js:167:23)
```
> fix(ntlm authentication)

- recipes/servers.md
As per source code ([`config-defaults.js`](https://github.com/johnpapa/lite-server/blob/master/lib/config-defaults.js#L16)) and documentation [(§ custom-configuration)](https://github.com/johnpapa/lite-server#custom-configuration) the first two `middleware` object keys are mapped to the default middleware provided by the package.
In my local development server I start from key `10` because it is a *round* number and ensures future added default middleware will not be overwritten. If you consider it might be better, I can change the example to start from key `2`.
> Update `lite-server` example

- .travis.yml
- README.md
- package.json
- test/e2e/http-proxy-middleware.spec.js
- test/unit/context-matcher.spec.js
- fix invalid glob patterns in tests
- fix typo in README.md 
- remove node 0.x support (EOL https://github.com/nodejs/Release#release-schedule1)
> chore(dependencies): update dependencies

- recipes/https.md
Hello again! :slightly_smiling_face:
Recently I was working with proxy requests to HTTPS servers. In my specific case I had to use a PKCS12 client certificate to authenticate on the remote server (the type you normally import in your browser).
After looking into the code and old issues of the [http-proxy](https://github.com/nodejitsu/node-http-proxy) package, I made a working example.
I already submitted a pull request there: nodejitsu/node-http-proxy#1209. I thought a little bit of documentation could help other people in the future, so I added a new `https.md` recipe.
> Add recipe for proxy to HTTPS servers

- lib/index.js
To reproduce supply a custom certificate with altnames (e.g. `localhost:5000`) that does not include `localhost:<port>` and start server on `localhost:<port>` (e.g. `localhost:3000`).
```
[HPM] Error occurred while trying to proxy request <redacted> from <redacted> to <redacted> (undefined) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
```
[HPM] Error occurred while trying to proxy request <redacted> from <redacted> to <redacted> (Error: Hostname/IP doesn't match certificate's altnames: "Host: <redacted>. is not in the cert's altnames: DNS:<redacted>, DNS:<redacted>") (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
> fix(log): Handle case when error code is missing

- .travis.yml
- CHANGELOG.md
- examples/connect/index.js
- examples/express/index.js
- examples/websocket/index.js
- package.json
- yarn.lock
> chore(dependencies): update micromatch@4 and dev dependencies

- dist/http-proxy-middleware.js
- examples/websocket/index.html
- package.json
- src/http-proxy-middleware.ts
> fix(ws): fix concurrent ws requests

- CHANGELOG.md
- examples/websocket/index.html
- package.json
- src/http-proxy-middleware.ts
> fix(ws): internal server upgrade

- README.md
- src/http-proxy-middleware.ts
- src/router.ts
- test/unit/router.spec.ts
hello,
this PR adds support for **options.router** for async handlers.
It came up in this issue: https://github.com/chimurai/http-proxy-middleware/issues/153
I would be glad to also add tests, but it seems like instructions are missing since it expects a running server on port 8000/3000.. please provide and i'll complete the tests
> feat: async router

- CHANGELOG.md
- package.json
- src/config-factory.ts
- src/context-matcher.ts
- src/handlers.ts
- src/http-proxy-middleware.ts
- src/index.ts
- src/logger.ts
- src/path-rewriter.ts
- src/router.ts
- src/types.ts
- test/e2e/_utils.ts
- test/e2e/express-router.spec.ts
- test/e2e/http-proxy-middleware.spec.ts
- test/e2e/path-rewriter.spec.ts
- test/e2e/router.spec.ts
- test/e2e/websocket.spec.ts
- test/types.spec.ts
- tsconfig.json
- yarn.lock
> feat(typescript): types support

- README.md
- src/http-proxy-middleware.ts
- src/types.ts
- test/types.spec.ts
- test/unit/path-rewriter.spec.ts
- yarn.lock
Related issue: https://github.com/chimurai/http-proxy-middleware/issues/374
> feat: async pathRewrite

- README.md
- src/types.ts
- test/e2e/router.spec.ts
- yarn.lock
* Fixes #407 
* Fixes #408 
* Explicit about `protocol` requiring `:` in README.
* Adds `https:` to router tests.
* Test `protocol: 'https'` to router tests showing `:` is required for `https` to work.
> fix(typescript): fix proxyRes and router types

- src/http-proxy-middleware.ts
- test/e2e/router.spec.ts
> fix(router): handle rejected promise in custom router

- package.json
exclude build artifact tsconfig.tsbuildinfo
before:
>npm notice package size:  30.3 kB                                 
>npm notice unpacked size: 208.4 kB                                
after:
>npm notice package size:  17.1 kB                                 
>npm notice unpacked size: 61.0 kB
> build(package): exclude build artifact tsconfig.tsbuildinfo

- package.json
- yarn.lock
fixes: https://github.com/chimurai/http-proxy-middleware/issues/439
https://www.npmjs.com/advisories/1486
> chore(deps): http-proxy 1.18.1

- recipes/async-response.md
Steven mergen deze handel :)
this solves #318 about async handling proxied response. I can now modify the response before piping it, and im able to set response headers before i actually sent the response. It was all in the lib itself, so native no tricks :)
if you want to check the flow here is the working example:
https://codesandbox.io/s/holy-resonance-yz552?file=/src/index.js
controller: restart server, now you will see this flow:
```
[HPM] Proxy created: /  -> http://localhost:3001
🚀 dummy service started on 3001
🚀 proxy started on 8080
proxyReq - test entry async is provided: da
target - async request header: da
onProxyRes
test - start: 200
test - response header: wei
test - end: { baba: 'yaga' }
```
the "wei" in the response header is set async and this validates it works :)
~~if …
> chore: show async response header

- src/handlers.ts
- test/unit/handlers.spec.ts
Currently `ETIMEDOUT` code is handled by the `defaultErrorHandler` as a `[500] Internal Server Error`. 
It should be handled as the regular `ECONNRESET` || `ENOTFOUND` || `ECONNREFUSED` || `ETIMEDOUT` codes.
> Preventing the fail of the 'ETIMEDOUT' code in 500 'Internal server error'

- package.json
- src/config-factory.ts
- src/handlers.ts
- src/path-rewriter.ts
- src/router.ts
- yarn.lock
`camelcase` and `is-plain-obj` are small, single purpose and
dependency free utilities with builtin TS support. They cover all
left lodash usages.
> refactor: replace lodash with small libraries

- CHANGELOG.md
- src/http-proxy-middleware.ts
- test/e2e/express-router.spec.ts
- test/e2e/http-proxy-middleware.spec.ts
fixes #189 
fixes #287
Example Graceful Shutdown (source: [https://expressjs.com](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html)):
```js
process.on('SIGTERM', () => {
debug('SIGTERM signal received: closing HTTP server')
server.close(() => {
debug('HTTP server closed')
})
})
```
More on graceful server shutdown: https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html
> fix(proxy): close proxy when server closes

- CHANGELOG.md
- src/handlers.ts
- test/unit/handlers.spec.ts
> fix(error handler): fix confusing error message

- CHANGELOG.md
- src/config-factory.ts
- src/http-proxy-middleware.ts
- test/unit/config-factory.spec.ts
> fix(option): optional `target` when `router` is used

- src/handlers.ts
- test/unit/handlers.spec.ts
Background:
With `router` usage and optional `target` (#512); Required `target` for http-proxy can sometimes be empty.
This PR will re-throw the error emitted from `http-proxy`.
`req` and `res` object are empty, so there is no graceful way to handle this error...
In these cases  it recommended to set `target` as fallback.
> fix(error handler): re-throw http-proxy missing target error

- CHANGELOG.md
- README.md
- package.json
- src/http-proxy-middleware.ts
> fix(log error): handle optional target

- README.md
- package.json
- src/handlers/fix-request-body.ts
- src/handlers/public.ts
- src/http-proxy-middleware.ts
- test/e2e/_utils.ts
- test/e2e/http-proxy-middleware.spec.ts
- yarn.lock
If a body parser middleware is added before the proxy is configured, proxying POST requests with bodies fails. This fixes that and provides a test, as requested by @chimurai in #460.
Code from #460 by @sarumont and from #320 by @repl-chris used -- thanks to both!
Fixes #90
Fixes #320
Fixes #417
> feat: try to proxy body even after body-parser middleware

- src/types.ts
I've been rewriting the handlers' types on my current project. To avoid it this PR extract handlers type and expose them
Also made the callbacks have the same types implemented on the [http-proxy](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51504fd999031b7f025220fab279f1b2155cbaff/types/http-proxy/index.d.ts)
> chore(typescript): extract handlers types

- jest.config.js
- test/e2e/test-kit.ts
I've noticed that the test coverage is collecting data from `dist` and `src`.
Improve the collaboration experience and maintenance. 
It will also enable a better `yarn test --watch` usability, cause the test-kit will look for the source code.
```
---------------------------|---------|----------|---------|---------|------------------------------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                        
---------------------------|---------|----------|---------|---------|------------------------------------------
All files                  |   84.66 |    72.65 |   82.07 |   84.95 |                                          
dist                      |    90.8 |    74.63 |   92.86 |   90.94 | …
```
> test(coverage): improve coverage config

- test/unit/fix-request-body.spec.ts
- test/unit/response-interceptor.spec.ts
Just add unit tests to cover some use cases for `fixRequestBody` and `responseInterceptor`
Unit tests for handlers
United
> Add test coverage to fixRequestBody and responseInterceptor

- src/handlers/fix-request-body.ts
fix type error when `fixRequestBody` is used.
caused by: #603
> fix(fixRequestBody): fix type error

- yarn.lock
deduplicate `yarn.lock` file with https://www.npmjs.com/package/yarn-deduplicate
Reduces size of `node_modules`
```shell
du -hcs node_modules
```
Before: **357M**
After: **236M**
`yarn test`
`yarn build`
> chore(yarn.lock): yarn-deduplicate

- package.json
- yarn.lock
- bump `mockttp`
- remove `resolution` workaround (conflicting `@types/express` from `mockttp`)
- CI
> chore(package): bump devDep mockttp

- package.json
- src/types.ts
Fix regression in types introduced in https://github.com/chimurai/http-proxy-middleware/pull/603
- fixes https://github.com/chimurai/http-proxy-middleware/issues/650
- fixes https://github.com/chimurai/http-proxy-middleware/issues/692
- fixes https://github.com/chimurai/http-proxy-middleware/pull/683
> fix(types): fix type regression

- recipes/response-interceptor.md
An update to the responseInterceptor recipe to include modifying headers
The recipe file did not include an example for modifying headers.
I was working on a proof of concept at my place of work, and trying to utilise http-proxy-middleware. I was struggling with modifying the response headers, the details in https://github.com/chimurai/http-proxy-middleware#http-proxy-events worked fine if you didn't want to use the response interceptor.
- [ x ] My change requires a change to the documentation.
> docs(response-interceptor.md): add headers modification example

- src/handlers/fix-request-body.ts
- test/unit/fix-request-body.spec.ts
It is common for POST request to have the content type: `application/x-www-form-urlencoded; charset=UTF-8`
The `charset` part can be set when you have a form with attribute `accept-charset="utf-8"`
I encountered this while using the `fixRequestBody` function and the content type check doesn't take the charset into account.
> fix(fix-request-body): improve content type check

- README.md
- examples/connect/index.js
- examples/express/index.js
- recipes/async-response.md
- recipes/basic.md
- recipes/servers.md
- src/http-proxy-middleware.ts
- src/types.ts
- test/e2e/http-proxy-middleware.spec.ts
Fixes incorrect usage of `originalUrl`. Introduced in https://github.com/chimurai/http-proxy-middleware/pull/18
Now you can modify the `baseUrl`; a feature which Express' `app.use` already provides..
```js
// mount on "/users" and keep the "/users" base path
app.use('/user', createProxyMiddleware({'target': 'https://jsonplaceholder.typicode.com/users'}))
// mount on "/users" and change the "/users" base path
app.use('/user', createProxyMiddleware({'target': 'https://jsonplaceholder.typicode.com/customers'}))
```
- https://github.com/chimurai/http-proxy-middleware/issues/225#issuecomment-351230574
- https://github.com/chimurai/http-proxy-middleware/discussions/541
- https://github.com/chimurai/http-proxy-middleware/pull/723#issuecomment-1068529477
- …
> fix: server mounting [BREAKING CHANGE]

- README.md
- src/http-proxy-middleware.ts
- src/types.ts
- test/e2e/plugins.spec.ts
- Write plugins to extend and share proxy functionality, while keeping the core functionality small and clean.
- Exposes internal http-proxy instance; ie. to subscribe to its events directly.
- https://github.com/chimurai/http-proxy-middleware/pull/190
- https://github.com/chimurai/http-proxy-middleware/pull/687
Allow plugins to be created for functionality like:
- https://github.com/chimurai/http-proxy-middleware/discussions/538
- https://github.com/chimurai/http-proxy-middleware/issues/477
- https://github.com/chimurai/http-proxy-middleware/issues/237
- unit tests
> feat(plugins): add support for plugins

- README.md
- src/get-plugins.ts
- src/http-proxy-middleware.ts
- src/types.ts
- test/unit/get-plugins.spec.ts
- add `ejectPlugins` option
http-proxy-middleware is configured with some default plugins for common use cases.
Allow the proxy behaviour to be fully customised with `ejectPlugins: true`.
- docs
- unit tests
> feat(ejectPlugins): skip registering default plugins

- README.md
- examples/browser-sync/index.js
- examples/connect/index.js
- examples/express/index.js
- examples/response-interceptor/index.js
- src/debug.ts
- src/handlers/response-interceptor.ts
- src/http-proxy-middleware.ts
- src/path-rewriter.ts
- src/plugins/default/debug-proxy-errors-plugin.ts
- src/plugins/default/logger-plugin.ts
- src/plugins/default/proxy-events.ts
- src/router.ts
- src/utils/function.ts
- test/e2e/http-proxy-middleware.spec.ts
- test/unit/utils/function.spec.ts
Verbose output to troubleshoot issues.
Add environment variable to enable verbose logging: `DEBUG=http-proxy-middleware*`
Improve troubleshooting
fixes https://github.com/chimurai/http-proxy-middleware/discussions/530
fixes https://github.com/chimurai/http-proxy-middleware/discussions/685
> feat(debug): improve troubleshooting

- MIGRATION.md
- README.md
- cspell.json
- examples/connect/index.js
- examples/express/index.js
- recipes/proxy-events.md
- recipes/websocket.md
- src/get-plugins.ts
- src/http-proxy-middleware.ts
- src/index.ts
- src/legacy/create-proxy-middleware.ts
- src/legacy/index.ts
- src/legacy/options-adapter.ts
- src/legacy/public.ts
- src/legacy/types.ts
- test/e2e/http-proxy-middleware.spec.ts
- test/legacy/http-proxy-middleware.spec.ts
- test/types.spec.ts
- test/unit/get-plugins.spec.ts
- Add `legacyCreateProxyMiddleware()` to use v3 with v2 behaviour.
- User's `onError` and `on.error` handler replaces default error handler.
- [MIGRATION.md](https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md)
V3 introduces some breaking changes:
https://github.com/chimurai/http-proxy-middleware/milestone/2?closed=1
Allow users to upgrade to v3 with minimal changes.
After upgrading you can [migrate](https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md) deprecated functionality at your own pace.
- unit tests
- unit tested patched webpack-dev-server with v3 (https://github.com/webpack/webpack-dev-server/commit/eea50f342e3090483f6da4932b84ed52bba44c58)
- webpack-dev-server: `npm run test:only -- --testNamePattern=proxy` …
> feat(legacyCreateProxyMiddleware): adapter with v2 behaviour

- src/legacy/options-adapter.ts
- test/legacy/http-proxy-middleware.spec.ts
Display upgrade tips when `legacyCreateProxyMiddleware()` is used with legacy features.
DX;
Allow users to use `legacyCreateProxyMiddleware()` as intermediate upgrade, before fully migrating to v3
- unit tests
> feat(legacyCreateProxyMiddleware): show migration tips

- src/_handlers.ts
Add default handler to http-proxy `econnreset` event.
This event is not documented in official documentation:
https://github.com/http-party/node-http-proxy#listening-for-proxy-events
It is typed in:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e626d3221693ea35ae4298bc8192ac4abebd225f/types/http-proxy/index.d.ts#L109
Event is emitted:
https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/passes/web-incoming.js#L158
Lack of this handler potentially causes server to crash (unconfirmed, difficult to replicate)
- https://github.com/webpack/webpack-dev-server/issues/1642
hotfix 🤞
> fix(error handler): add default handler to econnreset

- src/_handlers.ts
Add socket error handler for `proxyReqWs`
hopefully fixes: https://github.com/webpack/webpack-dev-server/issues/1642
related: https://github.com/chimurai/http-proxy-middleware/pull/759
Relying on feedback from: https://github.com/webpack/webpack-dev-server/issues/1642#issuecomment-1104325120
> fix(proxyReqWs): catch socket errors

- src/plugins/default/logger-plugin.ts
fixes
```
[HPM] GET undefinedundefined -> http://jsonplaceholder.typicode.com/users [304]
```
Next.js doesn't seem to expose the baseUrl (/api) ...
Manual
> fix(logger-plugin): fix next.js url logging (baseUrl not supported)

- recipes/response-interceptor.md
- Update `Text replacement` example for Response Interceptor
- In the `Replace text and change http status code` example, changing `Hello` to `Teapot` won't show anything since there is no `Hello` string in `http://www.example.com`
- Suggest to update string `Example`, also should use `replaceAll` since the `Example` is in the document title as well, so it maybe hard to notice the change
- Run an express app with target `http://www.example.com`
- Make sure the word `Example` is changed `Hello`
> docs(response-interceptor.md): improve example

- src/handlers/response-interceptor.ts
- src/http-proxy-middleware.ts
- src/legacy/options-adapter.ts
- src/path-filter.ts
- src/path-rewriter.ts
- src/plugins/default/error-response-plugin.ts
- src/types.ts
- test/e2e/express-error-middleware.spec.ts
- test/e2e/http-proxy-middleware.spec.ts
- test/e2e/plugins.spec.ts
- test/unit/response-interceptor.spec.ts
- tsconfig.json
Enable TypeScript `"strict": true`
> refactor: minor type improvements

- .github/workflows/ci.yml
Node v16 EOL: 2023-09-11
https://nodejs.org/en/blog/announcements/nodejs16-eol/
> ci: drop node v14 and v16

- recipes/response-interceptor.md
`responseInterceptor` expects its function argument to return a value that can be passed to `Buffer.from`.
The documentation is misleading.
Confirmed locally.
> docs(responseInterceptor): fix header manipulation example

- CHANGELOG.md
- src/plugins/default/logger-plugin.ts
- test/e2e/http-proxy-middleware.spec.ts
> fix(logger-plugin): fix missing target port

- .github/workflows/publish.yml
- .npmrc
- CHANGELOG.md
- package.json
https://github.blog/2023-04-19-introducing-npm-package-provenance
https://docs.npmjs.com/generating-provenance-statements
> ci(package): npm package provenance

- CHANGELOG.md
- src/factory.ts
- src/index.ts
- src/legacy/create-proxy-middleware.ts
- src/legacy/options-adapter.ts
- src/legacy/types.ts
fixes #1007
```shell
npx madge --circular src/index.ts
```
Before:
After:
> refactor: fix circular dependencies

- CHANGELOG.md
- src/handlers/fix-request-body.ts
- test/unit/fix-request-body.spec.ts
Enhance `fixRequestBody` method to fix `Content-Type` includes `+json`
Now, if our Media Type includes `+json` but does not includes `application/json`, the `fixRequestBody` method will not work. For example, the Media Type is `application/merge-patch+json`.
According to [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838#section-4.2.8), the `+` suffix indicates a structured type. Therefore, for the Media Type includes `+json`, we can directly serialize it to JSON.
This PR fixes the issue where the `fixRequestBody` method does not work for Media Types includes `+json`, such as `application/merge-patch+json`.
Unit Test
> fix(fix-request-body): support '+json' content-type suffix

- package.json
fix package.json warnings from: https://publint.dev/http-proxy-middleware
- add package.json `type: commonjs` (https://publint.dev/rules#use_type)
> chore(package.json): add type: commonjs

- src/plugins/default/logger-plugin.ts
> fix(logger-plugin): handle undefined protocol and hostname

- .github/workflows/ci.yml
add `dependencies` build step to install and cache dependencies 
Preventing this error when multiple jobs try to update/create the cache:
> Failed to save: Unable to reserve cache with key Linux-yarn-7f6dd4a8bff79fc4bd6feeff99e0401a54af1c318a2b7eebccb7590a85811e2e, another job may be creating this cache.
> ci(github-actions): pipeline improvements

- package.json
- patches/http-proxy+1.18.1.patch
- yarn.lock
use `patch-package` to patch `http-proxy`
removing this deprecation message:
```shell
[DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
```
> ci(package): patch http-proxy

- package.json
fix error during installation:
introduced by: https://github.com/chimurai/http-proxy-middleware/pull/1084
> build(patch-package): run patch-package in 'development' only

- .github/workflows/ci.yml
- src/handlers/fix-request-body.ts
- test/unit/fix-request-body.spec.ts
> fix(fixRequestBody): prevent multiple .write() calls

- src/handlers/fix-request-body.ts
- test/unit/fix-request-body.spec.ts
* fix(fixRequestBody): handle invalid request
> fix(fixRequestBody): handle invalid request

- src/handlers/fix-request-body.ts
- test/unit/fix-request-body.spec.ts
Adds Content-Type text/plain to bodies that are forwarded w/ fixRequestBody. Crucial since bodyParser handles that content-type.
Discovered this issue when a proxy server that was using bodyParser used fixRequestBody to forward bodies over to an API. The API would receive a request with a non-zero Content-Length but an empty body, so the API would be in deadlock trying to read from a stream that never would never have any data.
fixes [1102](https://github.com/chimurai/http-proxy-middleware/issues/1102)
I added a unit test for this case
> fix(fixRequestBody): support text/plain

- NODE_DEPRECATIONS.md
- cspell.json
- patches/tr46+0.0.3.patch
- patches/uri-js+4.4.1.patch
- patches/whatwg-url+5.0.0.patch
use `patch-package` to patch `punycode` require/import 
removing this deprecation message:
```shell
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```
> chore(deps): fix punycode node deprecation warning

- CHANGELOG.md
- cspell.json
- src/plugins/default/error-response-plugin.ts
- src/utils/sanitize.ts
- test/unit/utils/sanitize.spec.ts
> fix(error-response-plugin): sanitize input
