chimurai/http-proxy-middleware

README.md
index.js
lib/handlers.js
lib/utils.js
test/http-proxy-middleware.spec.js

Implemented support to rewrite paths: #3

feat: added rewritePath support

---

README.md
index.js
lib/handlers.js
package.json
test/context-matcher.spec.js
test/handlers.spec.js
test/http-proxy-middleware.spec.js
test/websocket.spec.js

Allow subscription to http proxy's error and proxyRes event

---

README.md
index.js
lib/handlers.js
lib/proxy-table.js
package.json
test/proxy-table.spec.js

feat: proxyTable

---

README.md
index.js
test/http-proxy-middleware.spec.js

This one should be solid.
Sorry for all the chaos. I've been sick. lol

Enable subscription to the http-proxy on onProxyReq event.

---

examples/websocket/index.html
index.js
test/websocket.spec.js

feat(proxyTable): add proxyTable support for ws

---

README.md
index.js
lib/handlers.js
lib/proxy-table.js
test/handlers.spec.js

Subscribe to http-proxy events: onProxyReqWs, onOpen, onClose
fixes #55

feature(options): onProxyReqWs, onOpen, onClose

---

recipes/modify-post.md

Added recipe modify-post.md

---

CHANGELOG.md
README.md
index.js
lib/path-rewriter.js
recipes/pathRewrite.md
test/path-rewriter.spec.js

feat(pathRewrite): support for custom pathRewrite function.

---

lib/index.js

fix(websocket): fixes websocket upgrade issue

---

recipes/delay.md

To fix in memory https://github.com/chimurai/http-proxy-middleware/issues/83

Recipe for delaying request/response

---

CHANGELOG.md
README.md
lib/config-factory.js
lib/index.js
lib/logger.js
lib/router.js
recipes/README.md
recipes/router.md
test/e2e/router.spec.js
test/unit/_libs.js
test/unit/router.spec.js

feat: router

---

README.md
recipes/README.md
recipes/pathRewrite.md

docs(pathRewrite): fix examples

---

.travis.yml

https://docs.travis-ci.com/user/reference/xenial/

ci(travis): use xenial

---

CHANGELOG.md
package.json
yarn.lock

chore(deps): update lodash

---

README.md
recipes/servers.md

docs(recipe): fastify example

---

CHANGELOG.md
package.json
src/handlers.ts
yarn.lock

remove `camelcase` in favour of [simple mapping of http-proxy events](https://github.com/chimurai/http-proxy-middleware/issues/513#issuecomment-812516025).
hopefully fixes #513

fix(camelcase): remove camelcase dependency

---

src/handlers/response-interceptor.ts
test/e2e/response-interceptor.spec.ts

fix(response interceptor): proxy original response headers

---

CHANGELOG.md
package.json
tsconfig.json

chore(package): drop node 10 [BREAKING CHANGE]

---

package.json
test/e2e/express-router.spec.ts
test/e2e/router.spec.ts
test/e2e/websocket.spec.ts
yarn.lock

Static ports in tests causing occasional failures.
- fix flakiness in certain tests
- allow parallel mutation testing with [StrykerJS](https://github.com/stryker-mutator/stryker-js)
Run `yarn test` in parallel in multiple terminals

refactor(test): fix flakiness

---

package.json
yarn.lock

- bump `@types/express`
- added `resolutions` to fix conflicts from `mockttp` -> `@types/express@^4.0.33`

chore(package): bump @types/express

---

package.json
test/e2e/websocket.spec.ts
yarn.lock

- bump devDependency `ws`
- fixed breaking changes introduced by `ws@8.x`

chore(package): bump devDep ws

---

src/_handlers.ts
test/unit/handlers.spec.ts

Fix a small typo: `occured` -> `occurred`

fix(_handlers.ts): typo

---

README.md

https://github.com/alanshaw/david/issues/179
david-dm.org no longer available
- [ x] Bug fix (non-breaking change which fixes an issue)

docs: remove david-dm badge

---

.husky/commit-msg
.husky/pre-commit

chore(husky): fix husky v7 hooks

---

package.json

feat(package): optional @types/express peer dependency

---

README.md
recipes/async-response.md
recipes/response-interceptor.md

fix proxy events documentation

docs(proxy events): fix new syntax

---

package.json
yarn.lock

https://github.com/micromatch/micromatch/commit/002d0d184c95e76775528fa1dbe0c446518879b2

chore(deps): update micromatch to 4.0.5

---

.github/workflows/ci.yml

- update `actions` to `v3`
- add node18 to unit-tests

ci: github-actions Node.js v18

---

package.json

- remove unnecessary pre-build steps
- related to #609
- speed up CI
- CI

ci: remove unnecessary pre-build steps

---

recipes/servers.md

docs(servers.md): next.js bodyParser usage

---

README.md

docs(README.md): add beta badge

---

recipes/proxy-events.md

The notation {'a', b} isn't syntactically correct nowadays, preferring {a: b}

docs(proxy-events.md): fix example

---

recipes/websocket.md

simple fix for proxy variable name, proxy is not defined but instead `socketProxy` is the correct variable name
was reading documentation and thought that this was an error
n/a
.md change

docs: fix documentation for websockets

---

CHANGELOG.md
src/types.ts

fixes https://github.com/chimurai/http-proxy-middleware/discussions/768#discussioncomment-9004484

fix(type): fix RequestHandler return type

---

CHANGELOG.md
src/errors.ts

refactor(errors): improve pathFilter error message

---

MIGRATION.md

Fix two misspelled URLs in MIGRATION.md.

docs(MIGRATION.md): fix misspelled URLs

---

yarn.lock

fixes https://github.com/chimurai/http-proxy-middleware/security/dependabot/51

chore(package): update ip dev dependency

---

src/index.ts

It seems that the Plugin type is not exported, it would be useful so we can type our custom plugins
Being able to correctly type our plugins
Used locally a forked version

feat(types): export Plugin type

---

CHANGELOG.md
src/types.ts
test/types.spec.ts

fix(types): fix Logger type

---

context7.json

https://github.com/upstash/context7/blob/master/docs/adding-projects.md

chore: add context7.json
